### ISSUE TITLE
Python version of v1.1.8 doesn't work due to the missing env.json

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#21]
**Describe the bug**
Python version of v1.1.8 doesn't work due to the missing env.json

**Traceback**
```python
 Traceback (most recent call last):
   File "c:/Users/helixvita/Dropbox/mpcproxies/git-helixvita/MTG-Proxyshop/main.py", line 25, in <module>
     from proxyshop.creator import CreatorPanels
   File "c:\Users\helixvita\Dropbox\mpcproxies\git-helixvita\MTG-Proxyshop\proxyshop\creator.py", line 13, in <module>
     from proxyshop import core
   File "c:\Users\helixvita\Dropbox\mpcproxies\git-helixvita\MTG-Proxyshop\proxyshop\core.py", line 13, in <module>
     from proxyshop import gdown
   File "c:\Users\helixvita\Dropbox\mpcproxies\git-helixvita\MTG-Proxyshop\proxyshop\gdown.py", line 23, in <module>
     from proxyshop.constants import con
   File "c:\Users\helixvita\Dropbox\mpcproxies\git-helixvita\MTG-Proxyshop\proxyshop\constants.py", line 320, in <module>
     with open(os.path.join(cwd, "proxyshop/env.json"), "r", encoding="utf-8") as api_keys:
 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\helixvita\\Dropbox\\mpcproxies\\git-helixvita\\MTG-Proxyshop\\proxyshop/env.json'
```

**Comment by MrTeferi** [comment]
Added env.json.dist and step to readme explaining
